name: setup-openapi
description: Set up GitHub Actions workflow with OpenAPI Generator
author: remarkablemark

inputs:
  version:
    description: OpenAPI Generator version
    required: false

runs:
  using: composite
  steps:
    - name: Install OpenAPI Generator CLI
      shell: sh
      run: npm install --global @openapitools/openapi-generator-cli

    - name: Set OpenAPI Generator Version
      if: inputs.version
      shell: sh
      run: openapi-generator-cli version-manager set $VERSION
      env:
        VERSION: ${{ inputs.version }}

branding:
  icon: check-circle
  color: green
