name: setup-openapi
description: Set up GitHub Actions workflow with OpenAPI Generator
author: remarkablemark

inputs:
  version:
    description: OpenAPI Generator version
    required: false

runs:
  using: composite
  steps:
    - name: Print version
      shell: bash
      run: |
        echo "version: $VERSION"
      env:
        VERSION: ${{ inputs.version }}

branding:
  icon: check-circle
  color: green
