name: test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run action
        uses: ./

      - name: Get version
        run: openapi-generator-cli version

      - name: Run action with version
        uses: ./
        with:
          version: 7.9.0

      - name: Check version
        shell: bash
        run: |
          if [[ $(openapi-generator-cli version) != '7.9.0' ]]; then
            echo 'Version does not match. See version below:'
            openapi-generator-cli --version
            exit 1
          fi

      - name: Run action with name
        uses: ./
        with:
          name: openapi-generator

      - name: Check name
        run: openapi-generator version
