name: test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Java
        if: matrix.os == 'windows-latest'
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Run action
        uses: ./

      - name: Get version
        run: openapi-generator-cli version

      - name: Run action with version
        uses: ./
        with:
          version: 7.9.0

      - name: Check version
        shell: bash
        run: |
          if [[ $(openapi-generator-cli version) != '7.9.0' ]]; then
            echo 'Version does not match. See version below:'
            openapi-generator-cli --version
            exit 1
          fi
